<a href="https://colab.research.google.com/github/Vasu-63/StackomaticASS1/blob/main/STACKOMATIC_ASSIGNMENT1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PART 1:PANDAS

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('california_housing_train.csv')# load as a dataframe
display(df.head(5),df.tail(10))#1. display first 5 rows and last 10 rows


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.0  
16991      1343.0       479.0         2.4805             73200.0  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

In [ ]:
df.describe() #2. Stasticial summary of data

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [ ]:
uniquebedrooms = df['total_bedrooms'].unique()#filter distinct numbers in total_bedrooms
no_uniquebedrooms = len(uniquebedrooms)#number of elements in uniquebedrooms

display(uniquebedrooms)
no_uniquebedrooms

array([1283., 1901.,  174., ..., 1637., 1308.,  936.])

1848

In [ ]:
newdf=df
newdf['total_bedrooms_per_total_rooms']=newdf['total_bedrooms']/newdf['total_rooms']#create new column
print(newdf['total_bedrooms_per_total_rooms'].mean())
print(newdf['total_bedrooms_per_total_rooms'].std())


0.21275998821034803
0.057823008903161756


In [ ]:
newdf[newdf['median_income']>5]#data filtering1

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  median_house_value  \
32          481.0       185.0         6.2558            146300.0   
69          952.0       360.0         5.4349            143000.0   
92          871.0       222.0         6.2715             97200.0   
98         1416.0       421.0         5.7843            110100.0   
100        1000.0       287.0         6.3814            159900.0   
...           ...         ...            ...                 ...   
16737       931.0       336.0         5.7664            267500.0   
16762       728.0       250.0         5.1005            266700.0   
16776       851.0       418.0         5.6445            364800.0   
16802      1030.0       308.0         5.9585            214900.0   
16899       516.0       181.0         5.0329            165600.0   

       total_bedrooms_per_total_rooms  
32                           0.172535  
69                           0.161077  
92                           0.153194  
98                           0.165998  
100                          0.140632  
...                               ...  
16737                        0.182945  
16762                        0.173856  
16776                        0.197642  
16802                        0.145982  
16899                        0.149449  

[3752 rows x 10 columns]

In [ ]:
newdf2=newdf[(newdf['total_rooms']>10000) & (newdf['median_house_value']<150000)]
display(newdf2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  median_house_value  \
133        4507.0      1807.0         2.2466             66800.0   
191        2453.0      1232.0         1.7844             78500.0   
198        3811.0      1570.0         4.0079            134500.0   
201        4122.0      1653.0         2.7219             74400.0   
229        6274.0      2095.0         2.4497             90900.0   
...           ...         ...            ...                 ...   
12654      6837.0      2358.0         3.1250            132500.0   
12772     28566.0      6082.0         2.3087            118800.0   
13388      9879.0      2152.0         2.5681             81300.0   
13707      6657.0      1874.0         4.9222            142900.0   
15436      6511.0      2267.0         3.5522            100100.0   

       total_bedrooms_per_total_rooms  
133                          0.224631  
191                          0.246715  
198                          0.203194  
201                          0.203059  
229                          0.245522  
...                               ...  
12654                        0.217481  
12772                        0.197536  
13388                        0.204803  
13707                        0.160860  
15436                        0.167858  

[67 rows x 10 columns]

In [ ]:
newdf.to_csv('newdata.csv')#saving file

# PART 2: NUMPY

In [ ]:
import numpy as np

In [ ]:
a=np.array([1]) #create array containing 1
i=2
while i<=20:
  a=np.append(a,i)#appending rest of the elements using while loop
  i=i+1
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
print(a[a%2==0]) #condition for evens

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
b=np.random.randint(10,101, size=(5, 4))
print(b)
c=b[:3,:2]#slicing 3 rows 2 columns
print(c)

[[44 10 99 35]
 [26 74 52 37]
 [19 47 86 59]
 [16 32 86 78]
 [54 99 49 86]]
[[44 10]
 [26 74]
 [19 47]]


In [ ]:
d=a.reshape(4,5) #reshaping a(array with first 20 numbers)
print(d)
e=d.reshape(20)
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
f=np.random.randint(1,5,size=(5,4))
print(f)
np.matmul(d,f)#matrix multiplication of d and f

[[2 1 3 1]
 [2 1 4 2]
 [1 4 2 1]
 [3 1 4 1]
 [4 4 2 2]]


array([[ 41,  39,  43,  22],
       [101,  94, 118,  57],
       [161, 149, 193,  92],
       [221, 204, 268, 127]])

In [ ]:
g=np.random.randint(0,101,size=(50))
h=g[g>50]#filtering using boolean
print(h)
index=np.array(g>50)#filtering using index
print(g[index])

[55 62 61 59 62 80 51 52 91 68 90 85 99 69 99 67 87 98 58 83 53 58 78 93
 55 57 99 81]
[55 62 61 59 62 80 51 52 91 68 90 85 99 69 99 67 87 98 58 83 53 58 78 93
 55 57 99 81]


In [ ]:
i=0
while i<4:
  print("column:",i+1,np.mean(b[:,i]),np.max(b[:,i]),np.sum(b[:,i]))#slicing all rows and i-th column
  i=i+1

column: 1 31.8 54 159
column: 2 52.4 99 262
column: 3 74.4 99 372
column: 4 59.0 86 295


In [ ]:
i=0
while i<4:
  mask=b[:,i]>np.mean(b[:,i])#creating a mask
  print("column:",i+1,b[mask,i])#printing using a mask and while loop
  i=i+1


column: 1 [44 54]
column: 2 [74 99]
column: 3 [99 86 86]
column: 4 [78 86]


# PART 3:PYTHON

In [ ]:
i=0
j=1
print(i)#1st number
print(j)#2nd number
while j+i<100:
  k=i+j
  print(k)
  i=j#setting i as j to contain second last number
  j=k#setting j as k to contain last number

0
1
1
2
3
5
8
13
21
34
55
89


In [ ]:
i=1
while i<=50:
  if i%3==0 and i%5==0:
    print("FizzBuzz")
  elif i%3==0:
    print("Fizz")
  elif i%5==0:
    print("Buzz")
  i=i+1

Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Buzz


In [ ]:
#function for median of list
def returnmedian(numbers):
  n = len(numbers)
  sorted_numbers = sorted(numbers)
  if n % 2 == 1: #creating different case for odd and even
    return sorted_numbers[n // 2]
  else:
    mid1 = sorted_numbers[n // 2 - 1]
    mid2 = sorted_numbers[n // 2]
    return (mid1 + mid2) / 2

In [174]:
#function for returning average of variable number of numbers
def average(*nums):
  if len(nums) == 0:
    return None # error handling
    return sum(nums) / len(nums)

In [177]:
#function for division considering error handling
def divide(a,b):
  if b==0:
    print("Can't divide by 0")
    return None
  else: return a/b